all_address_objects:
  ad01:
    ip: 192.168.10.100
  ad02:
    ip: 192.168.20.100
  rds01:
    ip: 192.168.10.10
  rds02:
    ip: 192.168.20.10
  admin:
    ip: 10.10.0.0/24
  web01:
    ip: 192.168.1.20
  web02:
    ip: 192.168.2.20
  db01:
    ip: 192.168.100.15
  db02:
    ip: 192.168.200.15
  backup01:
    ip: 192.168.15.30
  backup02:
    ip: 192.168.25.30

all_address_groups:
  ad:
  - ad01
  - ad02
  rds:
  - rds01
  - rds02
  web:
  - web01
  - web02
  db:
  - db01
  - db02
  backup:
  - backup01
  - backup02

all_service_objects:
  LDAPS:
    udp: 636
    tcp: 636
  LDAP_GC:
    tcp: 3268
  LDAP_GCTLS:
    tcp: 3269

all_service_groups:
  active_directory:
  - LDAP # Inbuilt
  - LDAPS
  - LDAP_UDP # Inbuilt
  - LDAP_GC
  - LDAP_GCTLS
  - KERBEROS # Inbuilt
  - DNS # Inbuilt
  - NTP # Inbuilt
  - SMB # Inbuilt
  - SAMBA # Inbuilt
  - DCE-RPC # Inbuilt
  web:
  - HTTP
  - HTTPS